### ISSUE TITLE
Proposal for adding to Wiki ?

### ISSUE THREAD

**Issue by threedslider** [YafaRay/libYafaRay#12]
Hi
It is nice to explain on how to use CMAKE and compiler to make the program from Yafaray version 3.5.1 for new users developer ?

What do you think @DavidBluecame of that ?

**Comment by DavidBluecame** [comment]
Hello,

I'm currently developing v4.0.0 which will be quite differently built respect to v3.5.1 (hopefully easier to build!). However it is a big work in progress and I'm still making major changes to the API.

If you want to build v3.5.1, that version is archived in https://github.com/YafaRay/Core

In the code of that link you will see a "building" section that explains how to build it in Linux step by step, for different distros. I hope it helps.
