### ISSUE TITLE
YafaRay's Wikipedia Page is in the Review Process of Being Taken Down

### ISSUE THREAD

**Issue by ghost** [YafaRay/libYafaRay#16]
The [Wikipedia article](https://en.wikipedia.org/wiki/YafaRay) is going to be possibly taken down due to long-standing Wikipedia guidelines violation. The alleged rule violation is [this](https://en.wikipedia.org/wiki/Wikipedia:N).

Letting whom it would concern know.

Thank you to all that maintains this project! (Love YafaRay!)

**Comment by ISO-101** [comment]
Closed as it was take down...
