### ISSUE TITLE
yafaray.org offline

### ISSUE THREAD

**Issue by hueldoeu** [YafaRay/libYafaRay#6]
i would like to visit the page.

**Comment by odil24** [comment]
> 
> 
> i would like to visit the page.

sorry, but the site is down now

**Comment by DavidBluecame** [comment]
Hello. I'm sorry but nothing I can do about this.

In any case please see this other open issue: https://github.com/YafaRay/libYafaRay/issues/2   You can see an archived version of the website, although it's slow and no longer interactive.

I'm closing this as a duplicate.
