### ISSUE TITLE
http://www.yafaray.org/ not working!

### ISSUE THREAD

**Issue by TrueGeometry** [YafaRay/libYafaRay#8]
The site that contains documentation is not working!

**Comment by DavidBluecame** [comment]
Hello,

Yes, unfortunately very true. Please see #2 where we have a discussion about that and there is a link there to an archived version of the site in Archive.org "wayback machine" that I hope it helps you for the time being. Apologies.

As this is already discussed in #2 I'm closing this particular issue to avoid having duplicates.

Thanks and best regards.
